### ISSUE TITLE
SmartThing App Not Controlling Device Model #H6159 and H6160

### ISSUE THREAD

**Issue by HRZ02** [uncdubdiver/smartthings-govee-led-lights#4]
So I think I have don everything right, and I can see that when I turn the power off through the Govee App, SmartThings shows that the device is off... but other then that I can't control the devices through the SmartThings App.  Any help would be appreciated. TIA

**Comment by uncdubdiver** [comment]
So I have H6159 so I know this works with that model, H6160 I don't have, but since it's RGB as well it should work fine too.
As for not being able to control it at all within the ST app, it might be that the device preferences in the device aren't setup properly (sorry I know I made this a little confusing to do with having to download a file and execute it locally to get the details).

The device preferences you need are:
1. Govee API Code - you get this from the govee app, user icon > About Us > Apply for API Key - the key should be emailed to you within a couple of minutes straight from Govee.
2. Download the index.html file that's in the repo and open it locally in your browser. Click on the Configuration tab, then enter in your Govee API Key and click Get Configuration.  On the returned response, keep up with the Model and Device ID.

Once you've got this information, login to account.smartthings.com with your account. Go to My Devices.  Search for the Govee Device you created that is assigned to the Govee LED Strips (DBDEV) handle (aka Type).  Click the device name to edit it.  On the edit page, under the Preferences row, click the (edit) link.  Enter in the 3 values that you have from #1 and #2 above, then click Save.
Next click My Device Handlers.  Click dbdevelopment : Govee LED Strips (DBDEV) to edit it.  In the top right, click Publish > For Me.

From here you should have full control of the Govee device within ST.  If not after this, then shoot me an email at db@deanberman.com and I'll work more directly with you.

GL!

**Comment by uncdubdiver** [comment]
Problem was the incorrect API key in the device value.
Now GTG, closing.
